name: HSSD-Investigations

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  FETCH:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: CI
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: Use Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' 
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        env:
          IDR_API_HSSD: ${{ secrets.IDR_API_HSSD }}
          FS_API: ${{ secrets.FS_API }}
        run: |
          python3 is-fs-hssd.py
      - name: save changes
        run: |
          git config --global user.email "bot-parser@users.noreply.github.com"
          git config --global user.name "Bot-Parser"
          DATE=$(date -Iseconds)
          git pull
          git commit --all --message "HSSD Updated by Bot-Parser on $DATE" || echo "no changes to commit"
          git push
