name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint.txt
    - name: save changes
      run: |
        git config --global user.email "pylinter@users.noreply.github.com"
        git config --global user.name "PyLinterr"
        DATE=$(date -Iseconds)
        git commit --all --message "Updated by PyLinter on $DATE" || echo "no changes to commit"
        git push

