name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint functioncheck.py | tee functioncheck.txt
        pylint is-fs-lexus.py | tee lexus.txt
        pylint is-fs-hssd.py | tee hssd.txt
        pylint is-fs-mhc.py | tee mhc.txt
        pylint is-fs-l4.py | tee labfour.txt
    - name: Upload pylint artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pylint report
        path: |
          functioncheck.txt
          lexus.txt
          hssd.txt
          mhc.txt
          labfour.txt
        
