name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint function_check.py | tee function_check.txt
        pylint insight_gunctions.py | tee insight_functions.txt
        pylint investigations.py | tee investigations.txt 
    - name: Upload pylint artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pylint report
        path: |
          functioncheck.txt
          InsightFunctions.txt
          Investigations.txt
        
